name: Setup Rust
inputs:
  target:
    description: Optional Rust target triple (e.g. x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, wasm32-wasi)
    required: false
    default: ""
runs:
  using: "composite"
  steps:
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ inputs.target }}
        components: clippy,rustfmt
    - uses: Swatinem/rust-cache@779680da715d629ac1d338a641029a2f4372abb5 # v2
      with:
        shared-key: rust-cache